version: '2'
services:

  #  The Application
  app:
    image: ariestattoo/app
    working_dir: /var/www
    volumes:
    - /var/www/storage
    env_file: '.env.prod'
    environment:
    - "DB_HOST=database"
    - "REDIS_HOST=cache"

  # The Web Server
  web:
    image: ariestattoo/web
    ports:
    - 80:80

  # The Database
  database:
    image: mysql:5.7
    volumes:
    - dbdata:/var/lib/mysql
    environment:
    - "MYSQL_DATABASE=ducks"
    - "MYSQL_USER=ducks"
    - "MYSQL_PASSWORD=ducks"
    - "MYSQL_ROOT_PASSWORD=ducks"

  # redis
  cache:
    image: redis:3.0-alpine

volumes:
  dbdata: