// AUTH
export const LOGGED = 'LOGGED'
export const USER = 'USER'

// SNACKBAR
export const SET_SNACKBAR_SHOW = 'SET_SNACKBAR_SHOW'
export const SET_SNACKBAR_COLOR = 'SET_SNACKBAR_COLOR'
export const SET_SNACKBAR_TEXT = 'SET_SNACKBAR_TEXT'
export const SET_SNACKBAR_SUBTEXT = 'SET_SNACKBAR_SUBTEXT'
export const SET_SNACKBAR_TIMEOUT = 'SET_SNACKBAR_TIMEOUT'

// USERS
export const SELECTED_USER = 'SELECTED_USER'
export const SET_USERS = 'SET_USERS'

// FEEDING
export const SET_APPLICATION_DATA = 'SET_APPLICATION_DATA'
export const SET_PENDING_FEEDINGS = 'SET_PENDING_FEEDINGS'
export const SET_PREVIOUS_FEEDINGS = 'SET_PREVIOUS_FEEDINGS'

